### ISSUE TITLE
Upgrading to jQuery 3.1.0 breaks hosted fields script

### ISSUE THREAD

**Issue by dan-at-unkubed** [UltraCart/hosted_fields#1]
Trying to update our carts to use jQuery 3.1.0, but the hosted fields script is choking on the call to the jQuery function:

.size()

which was deprecated in jQuery 1.8 and apparently removed in jQuery 3.  It can be replaced by

.length

which is completely backward compatible.

**Comment by ucjonathan** [comment]
Thanks for the feedback on that.  We've always used jQuery 1.11.3 with it since we published it which is after the deprecation was issued.  It should be a pretty save change to make.  

Have you already made the changes and tested the rest of hosted fields with jQuery 3 on your site?

**Comment by dan-at-unkubed** [comment]
Yeah, I copied the hosted-fields script to a local file, changed the eight
or so references of .size() to .length and everything seemed to work
correctly.  I ran a test transaction with the updated script, but not an
actual credit card.  Don't know if that qualifies as a valid test for your
QA or not, but that test transaction went through just fine.

Dan
