### ISSUE TITLE
Credit card number not getting updated with Cart.

### ISSUE THREAD

**Issue by him-developer** [UltraCart/hosted_fields#2]
We have a rest API based multi-step checkout process implemented. On the second last step we have a payment form which contains the hosted fields to collect Credit Card details. In few cases the CC number entered by user do not get updated with cart and user get Credit Card number is required error at finalize order call.
Can you provide us with some information why this may happen in some cases?
or
Give us some directions or tips to make this implementation good for all cases.

Regards,
HIM

**Comment by perrytew** [comment]
Him,
I missed this issue posting a while back.  Just noticed it.  Since it's been 3 months ... I'm hoping you found a solution.   Would you please update me as to your current needs?  Is this still an issue?

**Comment by him-developer** [comment]
Yes, issue was resolved and was at our end.
CartId was replaced after customer login and CC info was stored with previous one.

Thanks,
Him
