### ISSUE TITLE
`401 Unauthorized` response Error

### ISSUE THREAD

**Issue by chadhakavita** [UltraCart/hosted_fields#3]
I am getting following error.Please have a look and revert me ASAP:

Fatal error: Uncaught ultracart\v2\ApiException: [401] Client error: `GET https://secure.ultracart.com/rest/v2/checkout/cart?_expand=checkout%2Citems` resulted in a `401 Unauthorized` response: {"error":{"developer_message":"Permission Denied.","user_message":"Permission Denied."},"metadata":{}} in /home/dsdevelo/public_html/demo/CRM/vendor/UltraCart/rest_api_v2_sdk_php/lib/api/CheckoutApi.php:728 Stack trace: #0 /home/dsdevelo/public_html/demo/CRM/vendor/UltraCart/rest_api_v2_sdk_php/lib/api/CheckoutApi.php(703): ultracart\v2\api\CheckoutApi->getCartWithHttpInfo('checkout,items') #1 /home/dsdevelo/public_html/demo/CRM/sync.php(52): ultracart\v2\api\CheckoutApi->getCart('checkout,items') #2 {main} thrown in /home/dsdevelo/public_html/demo/CRM/vendor/UltraCart/rest_api_v2_sdk_php/lib/api/CheckoutApi.php on line 728

**Comment by ucjonathan** [comment]
Please post your issue to the proper GitHub project, include sample code, and XXXXX out any security keys in the code.
